spring:
  mvc:
    pathmatch:
#      使用swagger需要配置该项
      matching-strategy: ant_path_matcher
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: lg20010922
    url: jdbc:mysql://47.101.42.127:3306/errand?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8
  # redis配置
  redis:
    host: 47.101.42.127
    database: 0
    port: 6666
    password: lg20010922